In [1]:
import pandas as pd 
import numpy as np



In [2]:
#code for countVectorizer
from sklearn.feature_extraction.text  import CountVectorizer
d1="i love you"
d2="love you so much"
d3="i hate you"
documents=[d1,d2,d3]
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(documents)
print(X.toarray())
print(vectorizer.vocabulary_)

[[0 1 0 0 1]
 [0 1 1 1 1]
 [1 0 0 0 1]]
{'love': 1, 'you': 4, 'so': 3, 'much': 2, 'hate': 0}


In [3]:
df=pd.read_csv("newsgroups_train.csv")
df

text  target       category
0     From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1     From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2     From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3     From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4     From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space
...                                                 ...     ...            ...
1652  From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
1653  From: renes@ecpdsharmony.cern.ch (Rene S. Dutc...       1  comp.graphics
1654  From: xrcjd@resolve.gsfc.nasa.gov (Charles J. ...       2      sci.space
1655  From: dietz@cs.rochester.edu (Paul Dietz)\nSub...       2      sci.space
1656  From: jhwitten@cs.ruu.nl (Jurriaan Wittenberg)...       2      sci.space

[1657 rows x 3 columns]

In [4]:
df_test=pd.read_csv("newsgroups_test.csv")
df_test

text  target       category
0     From: mccall@mksol.dseg.ti.com (fred j mccall ...       2      sci.space
1     From: "Changyaw Wang" <wangc@cs.indiana.edu>\n...       1  comp.graphics
2     From: lioness@maple.circa.ufl.edu\nSubject: Te...       1  comp.graphics
3     From: hotopp@ami1.bwi.wec.com (Daniel T. Hotop...       1  comp.graphics
4     From: Ad-Robot@bobsbox.rent.com (Robotic Posti...       1  comp.graphics
...                                                 ...     ...            ...
1097  From: malek@pi.titech.ac.jp (Zidouri Abdelmale...       1  comp.graphics
1098  From: livesey@solntze.wpd.sgi.com (Jon Livesey...       0    alt.atheism
1099  From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...       0    alt.atheism
1100  From: beck@irzr17.inf.tu-dresden.de (Andre Bec...       1  comp.graphics
1101  From: 18084TM@msu.edu (Tom)\nSubject: Billboar...       2      sci.space

[1102 rows x 3 columns]

In [5]:
df.iloc[:,1:2]

target
0          2
1          1
2          0
3          1
4          2
...      ...
1652       1
1653       1
1654       2
1655       2
1656       2

[1657 rows x 1 columns]

In [6]:
train_df=pd.read_csv("nlp_train.csv")
train_df

text  target  \
0      I was wondering if anyone out there could enli...       7   
1      A fair number of brave souls who upgraded thei...       4   
2      well folks, my mac plus finally gave up the gh...       4   
3      \nDo you have Weitek's address/phone number?  ...       1   
4      From article <C5owCB.n3p@world.std.com>, by to...      14   
...                                                  ...     ...   
11309  DN> From: nyeda@cnsvax.uwec.edu (David Nye)\nD...      13   
11310  I have a (very old) Mac 512k and a Mac Plus, b...       4   
11311  I just installed a DX2-66 CPU in a clone mothe...       3   
11312  \nWouldn't this require a hyper-sphere.  In 3-...       1   
11313  Stolen from Pasadena between 4:30 and 6:30 pm ...       8   

                       category  
0                     rec.autos  
1         comp.sys.mac.hardware  
2         comp.sys.mac.hardware  
3                 comp.graphics  
4                     sci.space  
...                         ...  
11309                   sci.med  
11310     comp.sys.mac.hardware  
11311  comp.sys.ibm.pc.hardware  
11312             comp.graphics  
11313           rec.motorcycles  

[11314 rows x 3 columns]

In [7]:
test_df=pd.read_csv("nlp_test.csv")
test_df

text  target  \
0     I am a little confused on all of the models of...       7   
1     I'm not familiar at all with the format of the...       5   
2                                   \nIn a word, yes.\n       0   
3     \nThey were attacking the Iraqis to drive them...      17   
4     \nI've just spent two solid months arguing tha...      19   
...                                                 ...     ...   
7527  \n   Henry, if I read you correctly, you may b...      14   
7528  about\nthem on\n\nActually, I thought Macs wer...       4   
7529  I sent a version of this post out a while ago,...       9   
7530  I have this kit which includes the following :...       6   
7531  \nFine, but one of the points of this entire d...      15   

                    category  
0                  rec.autos  
1             comp.windows.x  
2                alt.atheism  
3      talk.politics.mideast  
4         talk.religion.misc  
...                      ...  
7527               sci.space  
7528   comp.sys.mac.hardware  
7529      rec.sport.baseball  
7530            misc.forsale  
7531  soc.religion.christian  

[7532 rows x 3 columns]

In [8]:
filtered_train=train_df[train_df['category'].isin(['alt.atheism','sci.space','comp.graphics'])]
filtered_train

text  target  \
3      \nDo you have Weitek's address/phone number?  ...       1   
4      From article <C5owCB.n3p@world.std.com>, by to...      14   
13     \n   {Description of "External Tank" option fo...      14   
15     \nDon't be so sure.  Look what happened to Jap...       0   
16     \nI certainly do use it whenever I have to do ...       1   
...                                                  ...     ...   
11275  \nThis sounds like another of Ali AbuTaha's 57...      14   
11276  A new alternative to Scouting for those "unacc...       0   
11286  \n\n\n\n\nThe HGA isn't all that reflective in...      14   
11289  I have a Diamond Speedstar 24X board that I wa...       1   
11312  \nWouldn't this require a hyper-sphere.  In 3-...       1   

            category  
3      comp.graphics  
4          sci.space  
13         sci.space  
15       alt.atheism  
16     comp.graphics  
...              ...  
11275      sci.space  
11276    alt.atheism  
11286      sci.space  
11289  comp.graphics  
11312  comp.graphics  

[1657 rows x 3 columns]

In [9]:
filtered_test=test_df[test_df['category'].isin(['alt.atheism','sci.space','comp.graphics'])]
filtered_test

text  target       category
2                                   \nIn a word, yes.\n       0    alt.atheism
9     :  \n: well, i have lots of experience with sc...       1  comp.graphics
14    \nProbably because it IS rape.\n\n\nSo nothing...       0    alt.atheism
17    Hello,\ni'm interested in those devices too.\n...       1  comp.graphics
20    This is an invitation to send articles to the ...       1  comp.graphics
...                                                 ...     ...            ...
7488  \n\namen.. I too have learned by example, spec...       1  comp.graphics
7492  \n: I agree, I had a hard feeling not believin...       0    alt.atheism
7496  \n\nYes a flotation tank, combined with florid...      14      sci.space
7505  Archive-name: atheism/overview\nAlt-atheism-ar...       0    alt.atheism
7527  \n   Henry, if I read you correctly, you may b...      14      sci.space

[1102 rows x 3 columns]

In [10]:
filtered_train.iloc[:,1:2]

target
3           1
4          14
13         14
15          0
16          1
...       ...
11275      14
11276       0
11286      14
11289       1
11312       1

[1657 rows x 1 columns]

In [11]:
filtered_train['category'].unique()

array(['comp.graphics', 'sci.space', 'alt.atheism'], dtype=object)

In [12]:
# print newstraining data of 5th article

print(filtered_train.iloc[4,0])


I certainly do use it whenever I have to do TIFF, and it usually works
very well.  That's not my point.  I'm >philosophically< opposed to it
because of its complexity.

This complexity has led to some programs' poor TIFF writers making
some very bizarre files, other programs' inability to load TIFF
images (though they'll save them, of course), and a general
inability to interchange images between different environments
despite the fact they all think they understand TIFF.

As the saying goes, "It's not me I'm worried about- it's all the
abuse of TIFF over the years, and I chalk it all up to the immense (and
unnecessary) complexity of the format.

In the words of the TIFF 5.0 spec, Appendix G, page G-1 (capitalized
emphasis mine):

"The only problem with this sort of success is that TIFF was designed
to be powerful and flexible, at the expense of simplicity.  It takes a
fair amount of effort to handle all the options currently defined in
this specification (PROBABLY NO APPLICATION DOES

In [13]:
# print(filtered_train.iloc[4]['text'])

In [14]:

print("Correlation Matrix:")
print(corr_matrix)
# Optionally, visualize it using a heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()
filtered_train.columns

Index(['text', 'target', 'category'], dtype='object')

In [15]:
print(filtered_train.shape)

(1657, 3)


In [16]:
print(f"Number of data samples (articles): {filtered_train.shape[0]}")


Number of data samples (articles): 1657


In [17]:
# 9. Print new training data target names (Labels)
filtered_train['target'].nunique()

filtered_train['category'].unique().tolist()

['comp.graphics', 'sci.space', 'alt.atheism']

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer=CountVectorizer()

filter_train=filtered_train.dropna(subset=['text']).astype(str)

X=vectorizer.fit_transform(filter_train['text'])
# print(x.toarray()[22])

# print(vectorizer.vocabulary_)
Y=filter_train['target']





print(X.shape)
print(Y.shape)

(1624, 23598)
(1624,)


In [19]:
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()
model.fit(X, Y)

BernoulliNB()

In [20]:
# x_test=df_test['text']

y_test=df_test['target']


In [21]:
# from sklearn.feature_extraction.text import CountVectorizer


# filtered=df_test.dropna(subset=['text'])
# test=filtered.astype(str)
# x_test=vectorizer.transform(test['text'])

# y_pred=model.predict(x_test)

x_test = vectorizer.transform(df_test['text'].astype(str))  # No fit here!
y_pred = model.predict(x_test)

y_pred

array(['14', '1', '1', ..., '0', '1', '14'], dtype='<U2')

In [22]:
print(x_test.shape)        # Features of test data
print(model.n_features_in_)  # Number of features model expects


(1102, 23598)
23598


In [23]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_test = df_test['target'].astype(str)  # Make sure this column exists and matches order

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Detailed report
print(classification_report(y_test, y_pred, zero_division=0))

# Confusion Matrix (optional)
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.5816696914700544
              precision    recall  f1-score   support

           0       0.94      0.88      0.91       319
           1       0.78      0.93      0.84       389
          14       0.00      0.00      0.00         0
           2       0.00      0.00      0.00       394

    accuracy                           0.58      1102
   macro avg       0.43      0.45      0.44      1102
weighted avg       0.55      0.58      0.56      1102

[[281  31   7   0]
 [  4 360  25   0]
 [  0   0   0   0]
 [ 13  73 308   0]]


In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Vectorize training data
tfidf_vectorizer = TfidfVectorizer()
X_train = tfidf_vectorizer.fit_transform(filtered_train['text'].astype(str))
y_train = filtered_train['target']

# Train model
model = MultinomialNB()
model.fit(X_train, y_train)

# Vectorize test data
X_test = tfidf_vectorizer.transform(filtered_test['text'].astype(str))
y_test = filtered_test['target']

# Predict
y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Optional: Classification report
print(classification_report(y_test, y_pred, zero_division=0))


Accuracy: 0.8620689655172413
              precision    recall  f1-score   support

           0       0.92      0.76      0.84       319
           1       0.93      0.88      0.90       389
          14       0.78      0.92      0.84       394

    accuracy                           0.86      1102
   macro avg       0.88      0.86      0.86      1102
weighted avg       0.87      0.86      0.86      1102

